# dependabot config

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      test-dependencies:
        patterns:
          - "github.com/onsi/ginkgo*"
          - "github.com/onsi/gomega*"
      prod-dependencies:
        exclude-patterns:
          - "github.com/onsi/ginkgo*"
          - "github.com/onsi/gomega*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
