package cmd

import (
	"fmt"

	"github.com/go-logr/logr"
	"github.com/spf13/cobra"

	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/replay"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/runtime"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/viper"
)

// replayRun indirects through a package-level var (rather than calling
// replay.Run directly) so unit tests can substitute a fake here without
// needing to perform real tar extraction or Pyxis network calls;
// internal/replay has its own thorough test coverage of the real
// implementation.
var replayRun = replay.Run

// submitOfflineArtifactsCmd implements "submit-offline-artifacts": revalidating
// and submitting results generated by a disconnected (offline) run.
//
// This is a sub-command of `check container` specifically so it can reuse
// checkContainerCmd's own persistent --pyxis-api-token/--pyxis-host/
// --pyxis-env/--certification-component-id flags (and their PFLT_* env var
// bindings) rather than declaring a second, independent set of flags bound
// to different viper keys.
func submitOfflineArtifactsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "submit-offline-artifacts <path-to-artifacts.tar>",
		Short: "Revalidate and submit results generated by a disconnected (offline) run",
		Long: `This command takes the artifacts.tar produced by "preflight check container --offline"
on a disconnected host, copies it to a host with access to Red Hat services, and:
  - Revalidates the BasedOnUbi check, which could not reach Pyxis while offline.
  - Preserves every other result that was already completed offline.
  - Submits the finalized results to Red Hat, without requiring you to
    construct or run any Pyxis API calls by hand.`,
		Example: "  preflight check container submit-offline-artifacts ./artifacts/artifacts.tar",
		Args:    cobra.ExactArgs(1),
		// checkContainerCmd's own certification-component-id validation is
		// declared as a plain (non-persistent) PreRunE - not
		// PersistentPreRunE - specifically so it doesn't shadow rootCmd's
		// PersistentPreRun (which sets up the logr logger in context) for
		// this sub-command. So it's called explicitly here instead of
		// relying on cobra's persistent-hook inheritance.
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if err := validateCertificationComponentID(cmd, args); err != nil {
				return err
			}
			return validateSubmitOfflineArtifactsFlags()
		},
		RunE: submitOfflineArtifactsRunE,
	}

	flags := cmd.Flags()
	viper := viper.Instance()

	flags.String("extract-dir", "", "Directory to extract the artifacts tarball into. Defaults to a temporary directory.")
	_ = viper.BindPFlag("submit_offline_artifacts_extract_dir", flags.Lookup("extract-dir"))

	return cmd
}

// validateSubmitOfflineArtifactsFlags ensures the Pyxis credentials required
// to submit are present, since submit-offline-artifacts always submits (there
// is no dry-run mode). Legacy "ospid-" component ID normalization is already
// handled by validateCertificationComponentID, which is called explicitly
// just before this in submitOfflineArtifactsCmd's PreRunE.
func validateSubmitOfflineArtifactsFlags() error {
	v := viper.Instance()

	if v.GetString("certification_component_id") == "" {
		return fmt.Errorf("certification component ID must be specified to submit offline artifacts")
	}
	if v.GetString("pyxis_api_token") == "" {
		return fmt.Errorf("pyxis API Token must be specified to submit offline artifacts")
	}

	return nil
}

func submitOfflineArtifactsRunE(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()
	logger, err := logr.FromContext(ctx)
	if err != nil {
		//coverage:ignore
		return fmt.Errorf("invalid logging configuration")
	}

	v := viper.Instance()

	cfg, err := runtime.NewConfigFrom(*v)
	if err != nil {
		//coverage:ignore
		return fmt.Errorf("invalid configuration: %w", err)
	}

	opts := replay.Options{
		ArtifactsTarPath:         args[0],
		ExtractDir:               v.GetString("submit_offline_artifacts_extract_dir"),
		PyxisHost:                cfg.PyxisHost,
		PyxisAPIToken:            cfg.PyxisAPIToken,
		CertificationComponentID: cfg.CertificationComponentID,
		DockerConfig:             cfg.DockerConfig,
		Submit:                   true,
	}

	cmd.SilenceUsage = true

	summary, err := replayRun(ctx, opts)
	if err != nil {
		return err
	}

	logger.Info("submit-offline-artifacts complete",
		"extractDir", summary.ExtractDir,
		"basedOnUbiPassed", summary.BasedOnUbiPased,
		"submitted", summary.Submitted,
	)

	return nil
}
