package cmd

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/go-logr/logr"
	"github.com/spf13/cobra"

	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/check"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/replay"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/runtime"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/viper"
)

// replaySubmitCmd implements the "replay-submit" POC for revalidating and
// submitting results generated by a disconnected (offline) run.
//
// This is intentionally a sub-command of `check container` for now so we can
// get working code in front of DCI/cert-ops for UX feedback before deciding
// on final placement.
func replaySubmitCmd() *cobra.Command {
	replaySubmitCmd := &cobra.Command{
		Use:   "replay-submit <path-to-artifacts.tar-or-artifacts-root>",
		Short: "Revalidate and submit results generated by a disconnected (offline) run",
		Long: `This command takes artifacts produced by "preflight check container --offline"
on a disconnected host, copies them to a host with access to Red Hat services, and:
  - Revalidates the BasedOnUbi check, which could not reach Pyxis while offline.
  - Preserves every other result that was already completed offline.
  - Optionally submits the finalized results to Red Hat (with --submit), without
    requiring you to construct or run any Pyxis API calls by hand.

The argument may be either:
  - A single artifacts.tar file (single-architecture images), or
  - The root of a multi-arch "--artifacts" directory containing one
    "<platform>/artifacts.tar" per architecture, as produced when
    "check container --offline" is run against a manifest-list image.
    Every discovered platform is revalidated (and submitted) independently,
    since each architecture has its own image layers.`,
		Example: fmt.Sprintf("  %s\n  %s",
			"preflight check container replay-submit ./artifacts/artifacts.tar --submit",
			"preflight check container replay-submit ./artifacts --submit  # multi-arch: ./artifacts/<platform>/artifacts.tar"),
		Args:    cobra.ExactArgs(1),
		PreRunE: validateReplaySubmitFlags,
		RunE:    replaySubmitRunE,
	}

	flags := replaySubmitCmd.Flags()

	viper := viper.Instance()

	flags.String("extract-dir", "", "Directory to extract the artifacts tarball into. Defaults to a temporary directory.")
	_ = viper.BindPFlag("replay_extract_dir", flags.Lookup("extract-dir"))

	flags.BoolP("submit", "s", false, "Submit the finalized results to Red Hat after revalidating BasedOnUbi. "+
		"Without this flag, results.json is updated on disk but nothing is sent.")
	_ = viper.BindPFlag("replay_submit", flags.Lookup("submit"))

	// NOTE: these use replay-specific viper keys (not the shared "pyxis_api_token"
	// etc. keys that checkContainerCmd's own flags are bound to). Binding a second,
	// independent flag object to those shared keys would silently overwrite
	// checkContainerCmd's bindings for the lifetime of the process (since command
	// construction happens once at startup), breaking `check container --submit`
	// even when replay-submit is never invoked. viper.BindEnv keeps the documented
	// PFLT_* environment variable names working despite the internal key rename.
	flags.String("pyxis-api-token", "", "API token for Pyxis authentication (env: PFLT_PYXIS_API_TOKEN)")
	_ = viper.BindPFlag("replay_pyxis_api_token", flags.Lookup("pyxis-api-token"))
	_ = viper.BindEnv("replay_pyxis_api_token", "PFLT_PYXIS_API_TOKEN")

	flags.String("pyxis-host", "", "Host to use for Pyxis submissions. This will override Pyxis Env. (env: PFLT_PYXIS_HOST)")
	_ = viper.BindPFlag("replay_pyxis_host", flags.Lookup("pyxis-host"))
	_ = viper.BindEnv("replay_pyxis_host", "PFLT_PYXIS_HOST")

	flags.String("pyxis-env", check.DefaultPyxisEnv, "Env to use for Pyxis submissions.")
	_ = viper.BindPFlag("replay_pyxis_env", flags.Lookup("pyxis-env"))

	flags.String("certification-component-id", "", "Certification component ID from connect.redhat.com/component/view/{certification-component-id}\n"+
		"(env: PFLT_CERTIFICATION_COMPONENT_ID)")
	_ = viper.BindPFlag("replay_certification_component_id", flags.Lookup("certification-component-id"))
	_ = viper.BindEnv("replay_certification_component_id", "PFLT_CERTIFICATION_COMPONENT_ID")

	return replaySubmitCmd
}

// validateReplaySubmitFlags mirrors the same submit-flag validation used by
// `check container --submit` (see validateCertificationComponentID in
// check_container.go) since replay-submit's whole purpose is to submit, and
// applies the same legacy "ospid-" component ID normalization so pasting an
// ID straight from connect.redhat.com's legacy URL format still works.
func validateReplaySubmitFlags(cmd *cobra.Command, args []string) error {
	v := viper.Instance()

	// Normalize a legacy "ospid-<id>" component ID to just "<id>", same as
	// validateCertificationComponentID does for `check container`.
	componentID := v.GetString("replay_certification_component_id")
	parts := strings.Split(componentID, "-")
	if len(parts) > 2 {
		return fmt.Errorf("certification component id: %s is improperly formatted see help command for instructions on obtaining proper value", componentID)
	}
	if parts[0] == "ospid" {
		v.Set("replay_certification_component_id", parts[1])
	}

	if !v.GetBool("replay_submit") {
		return nil
	}

	if v.GetString("replay_certification_component_id") == "" {
		return fmt.Errorf("certification component ID must be specified when --submit is present")
	}
	if v.GetString("replay_pyxis_api_token") == "" {
		return fmt.Errorf("pyxis API Token must be specified when --submit is present")
	}

	return nil
}

func replaySubmitRunE(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()
	logger, err := logr.FromContext(ctx)
	if err != nil {
		//coverage:ignore
		return fmt.Errorf("invalid logging configuration")
	}

	v := viper.Instance()

	opts := replay.Options{
		ExtractDir:               v.GetString("replay_extract_dir"),
		PyxisHost:                runtime.PyxisHostLookup(v.GetString("replay_pyxis_env"), v.GetString("replay_pyxis_host")),
		PyxisAPIToken:            v.GetString("replay_pyxis_api_token"),
		CertificationComponentID: v.GetString("replay_certification_component_id"),
		DockerConfig:             v.GetString("dockerConfig"),
		Submit:                   v.GetBool("replay_submit"),
	}

	cmd.SilenceUsage = true

	path := args[0]
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("could not access %s: %w", path, err)
	}

	// A directory is treated as a multi-arch artifacts root
	// (<root>/<platform>/artifacts.tar per architecture); a file is treated
	// as a single artifacts.tar (single-architecture image).
	if info.IsDir() {
		return runReplaySubmitBatch(ctx, logger, path, opts)
	}

	opts.ArtifactsTarPath = path
	summary, err := replay.Run(ctx, opts)
	if err != nil {
		return err
	}

	logger.Info("replay-submit complete",
		"extractDir", summary.ExtractDir,
		"basedOnUbiPassed", summary.BasedOnUbiPased,
		"submitted", summary.Submitted,
	)

	return nil
}

// runReplaySubmitBatch handles the multi-arch case: root contains one
// "<platform>/artifacts.tar" per architecture (the layout
// `check container --offline` produces for a manifest-list image). Every
// platform is processed independently; one platform's failure does not stop
// the others from being revalidated/submitted.
func runReplaySubmitBatch(ctx context.Context, logger logr.Logger, root string, opts replay.Options) error {
	batch, err := replay.RunBatch(ctx, root, opts)
	if err != nil {
		return err
	}

	for platform, summary := range batch.Platforms {
		logger.Info("replay-submit complete for platform",
			"platform", platform,
			"extractDir", summary.ExtractDir,
			"basedOnUbiPassed", summary.BasedOnUbiPased,
			"submitted", summary.Submitted,
		)
	}

	for platform, platformErr := range batch.Errors {
		logger.Error(platformErr, "replay-submit failed for platform", "platform", platform)
	}

	if !batch.AllSucceeded() {
		return fmt.Errorf("replay-submit failed for %d of %d platform(s); see logs above for details",
			len(batch.Errors), len(batch.Errors)+len(batch.Platforms))
	}

	return nil
}
