package cmd

import (
	"fmt"

	"github.com/go-logr/logr"
	"github.com/spf13/cobra"

	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/check"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/replay"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/runtime"
	"github.com/redhat-openshift-ecosystem/openshift-preflight/internal/viper"
)

// replaySubmitCmd implements the "replay-submit" POC described in
// https://redhat.atlassian.net/browse/EDPP-331 and
// https://redhat.atlassian.net/browse/CERTSA-71.
//
// This is intentionally a sub-command of `check container` for now (per
// Adam Cornett's suggestion on CERTSA-71) so we can get working code in
// front of DCI/cert-ops for UX feedback before deciding on final placement.
func replaySubmitCmd() *cobra.Command {
	replaySubmitCmd := &cobra.Command{
		Use:   "replay-submit <path-to-artifacts.tar>",
		Short: "Revalidate and submit results generated by a disconnected (offline) run",
		Long: `This command takes an artifacts.tar produced by "preflight check container --offline"
on a disconnected host, copies it to a host with access to Red Hat services, and:
  - Revalidates the BasedOnUbi check, which could not reach Pyxis while offline.
  - Preserves every other result that was already completed offline.
  - Optionally submits the finalized results to Red Hat (with --submit), without
    requiring you to construct or run any Pyxis API calls by hand.`,
		Example: fmt.Sprintf("  %s", "preflight check container replay-submit ./artifacts/artifacts.tar --submit"),
		Args:    cobra.ExactArgs(1),
		PreRunE: validateReplaySubmitFlags,
		RunE:    replaySubmitRunE,
	}

	flags := replaySubmitCmd.Flags()

	viper := viper.Instance()

	flags.String("extract-dir", "", "Directory to extract the artifacts tarball into. Defaults to a temporary directory.")
	_ = viper.BindPFlag("replay_extract_dir", flags.Lookup("extract-dir"))

	flags.BoolP("submit", "s", false, "Submit the finalized results to Red Hat after revalidating BasedOnUbi. "+
		"Without this flag, results.json is updated on disk but nothing is sent.")
	_ = viper.BindPFlag("replay_submit", flags.Lookup("submit"))

	flags.String("pyxis-api-token", "", "API token for Pyxis authentication (env: PFLT_PYXIS_API_TOKEN)")
	_ = viper.BindPFlag("pyxis_api_token", flags.Lookup("pyxis-api-token"))

	flags.String("pyxis-host", "", "Host to use for Pyxis submissions. This will override Pyxis Env. (env: PFLT_PYXIS_HOST)")
	_ = viper.BindPFlag("pyxis_host", flags.Lookup("pyxis-host"))

	flags.String("pyxis-env", check.DefaultPyxisEnv, "Env to use for Pyxis submissions.")
	_ = viper.BindPFlag("pyxis_env", flags.Lookup("pyxis-env"))

	flags.String("certification-component-id", "", "Certification component ID from connect.redhat.com/component/view/{certification-component-id}\n"+
		"(env: PFLT_CERTIFICATION_COMPONENT_ID)")
	_ = viper.BindPFlag("certification_component_id", flags.Lookup("certification-component-id"))

	return replaySubmitCmd
}

// validateReplaySubmitFlags mirrors the same submit-flag validation used by
// `check container --submit` (see validateCertificationComponentID in
// check_container.go) since replay-submit's whole purpose is to submit.
func validateReplaySubmitFlags(cmd *cobra.Command, args []string) error {
	v := viper.Instance()

	if !v.GetBool("replay_submit") {
		return nil
	}

	if v.GetString("certification_component_id") == "" {
		return fmt.Errorf("certification component ID must be specified when --submit is present")
	}
	if v.GetString("pyxis_api_token") == "" {
		return fmt.Errorf("pyxis API Token must be specified when --submit is present")
	}

	return nil
}

func replaySubmitRunE(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()
	logger, err := logr.FromContext(ctx)
	if err != nil {
		//coverage:ignore
		return fmt.Errorf("invalid logging configuration")
	}

	v := viper.Instance()

	opts := replay.Options{
		ArtifactsTarPath:         args[0],
		ExtractDir:               v.GetString("replay_extract_dir"),
		PyxisHost:                runtime.PyxisHostLookup(v.GetString("pyxis_env"), v.GetString("pyxis_host")),
		PyxisAPIToken:            v.GetString("pyxis_api_token"),
		CertificationComponentID: v.GetString("certification_component_id"),
		DockerConfig:             v.GetString("dockerConfig"),
		Submit:                   v.GetBool("replay_submit"),
	}

	cmd.SilenceUsage = true

	summary, err := replay.Run(ctx, opts)
	if err != nil {
		return err
	}

	logger.Info("replay-submit complete",
		"extractDir", summary.ExtractDir,
		"basedOnUbiPassed", summary.BasedOnUbiPased,
		"submitted", summary.Submitted,
	)

	return nil
}
