name: Go

on:
  pull_request:
    branches:
    - main
    - release-*

jobs:
  build:
    # TODO: Set explicit permissions for this job.
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Install system deps
      run: 'sudo apt update && sudo apt install -y libgpgme-dev libbtrfs-dev libdevmapper-dev'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Tidy
      run: make tidy

    - name: Vet
      run: make vet

    - name: Format
      run: make fmt

    - name: Run golangci linting checks
      run: make lint

    - name: Test
      run: make cover

    - name: Coveralls
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.out

    - name: Build Multi-arch-linux
      run: make build-multi-arch-linux

    - name: Build Multi-arch-mac
      run: make build-multi-arch-mac
