name: Create Release Artifacts

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      registry:
        required: true
      user:
        required: true
      password:
        required: true
      token:
        required: true
        
jobs:
  release-assets-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux ]
        architecture:
          - amd64
          - arm64
          - ppc64le
          - s390x
    steps:
    - name: Docker Login
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
      with:
        registry: ${{ secrets.registry }}
        username: ${{ secrets.user }}
        password: ${{ secrets.password }}

    - name: Extract executable
      uses: shrink/actions-docker-extract@f1ef61065b78731fe3310b4e84e511f6a927a77e # v4.0.0
      id: extract
      with:
        image: ${{ secrets.registry }}/${{ inputs.name }}:${{ inputs.tag }}-${{ matrix.platform }}-${{ matrix.architecture }}
        path: /usr/local/bin/preflight

    - name: Rename and upload the binary
      run: |
        mv --verbose "${outputs_dir}/preflight" "${outputs_dir}/preflight-${platform}-${architecture}"
        gh release upload --repo "${GITHUB_REPOSITORY}" "${tag}" "${outputs_dir}/preflight-${platform}-${architecture}"
      env:
        outputs_dir: ${{ steps.extract.outputs.destination }}
        platform: ${{ matrix.platform }}
        architecture: ${{ matrix.architecture }}
        tag: ${{ inputs.tag }}
        GH_TOKEN: ${{ secrets.token }}

  # builds mac binaries in parallel using matrix strategy
  add-darwin-bins:
    name: Release binaries for MacOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set Env Tags
        run: echo "RELEASE_TAG=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)" >> "${GITHUB_ENV}"
  
      - name: Install system deps
        run: 'sudo apt update && sudo apt install -y libgpgme-dev libbtrfs-dev libdevmapper-dev'
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - name: Build Mac binary for ${{ matrix.architecture }}
        run: make build-mac-${{ matrix.architecture }}

      - name: Upload binary to the release
        run:
          gh release upload --repo "${GITHUB_REPOSITORY}" "${tag}" preflight-darwin-${{ matrix.architecture }}
        env:
          tag: ${{ inputs.tag }}
          GH_TOKEN: ${{ secrets.token }}
